# Generated by Django 5.1.1 on 2025-02-14 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
